- CHANGELOG.md
- CMakeLists.txt
- example/http-server-fast/http_server_fast.cpp
- include/beast/core/buffer_prefix.hpp
- include/beast/core/detail/buffers_ref.hpp
- include/beast/core/detail/cpu_info.hpp
- include/beast/core/detail/in_place_init.hpp
- include/beast/core/file.hpp
- include/beast/core/file_posix.hpp
- include/beast/core/impl/buffer_prefix.ipp
- include/beast/http/impl/serializer.ipp
- include/beast/http/impl/write.ipp
- include/beast/http/serializer.hpp
- include/beast/version.hpp
- test/http/file_body.cpp
- test/http/serializer.cpp
* Use file_body for valid requests, string_body otherwise.
* Construct buffer_prefix_view in-place
* Shrink serializer buffers using buffers_ref
* Tidy up BEAST_NO_BIG_VARIANTS
* Shrink serializer buffers using buffers_ref
* Add serializer::limit
Documentation preview:
http://vinniefalco.github.io/stage/beast/v75
> Version 75

- CHANGELOG.md
- CMakeLists.txt
- README.md
- doc/qbk/00_main.qbk
- include/boost/beast/core/handler_ptr.hpp
- include/boost/beast/http/fields.hpp
- include/boost/beast/http/impl/basic_parser.ipp
- include/boost/beast/version.hpp
- include/boost/beast/zlib/detail/deflate_stream.hpp
- test/CMakeLists.txt
- test/beast/core/handler_alloc.cpp
- test/beast/http/basic_parser.cpp
- test/beast/http/read.cpp
- test/beast/websocket/stream.cpp
* Fix typo in test/CMakeLists.txt
* basic_fields::value_type is not copyable
* Update repository links in source comments
* Ignore Content-Length in some cases
* Tidy up doc snippet paths
* Use off-site doc link
> Version 92

- CHANGELOG.md
- CMakeLists.txt
- README.md
- doc/Jamfile
- example/advanced/server-flex/advanced_server_flex.cpp
- example/advanced/server/advanced_server.cpp
- example/http/server/async-ssl/http_server_async_ssl.cpp
- example/http/server/async/http_server_async.cpp
- example/http/server/stackless-ssl/http_server_stackless_ssl.cpp
- example/http/server/stackless/http_server_stackless.cpp
- example/websocket/server/async-ssl/websocket_server_async_ssl.cpp
- example/websocket/server/async/websocket_server_async.cpp
- example/websocket/server/stackless-ssl/websocket_server_stackless_ssl.cpp
- example/websocket/server/stackless/websocket_server_stackless.cpp
- include/boost/beast/core/impl/file_win32.ipp
- include/boost/beast/http/impl/write.ipp
- include/boost/beast/version.hpp
- index.html
- test/beast/http/write.cpp
* file_win32 opens for read-only in shared mode
* Remove unused strands in server examples
* Update build instructions
* Doc root is at index.html
HTTP:
* Fix writing header into std::ostream
> Version 118

- .travis.yml
- CHANGELOG.md
- CMakeLists.txt
- README.md
- doc/qbk/04_http/03_streams.qbk
- example/common/detect_ssl.hpp
- example/common/session_alloc.hpp
- example/common/ssl_stream.hpp
- example/echo-op/echo_op.cpp
- include/boost/beast/core/buffered_read_stream.hpp
- include/boost/beast/core/file_win32.hpp
- include/boost/beast/core/impl/buffered_read_stream.ipp
- include/boost/beast/core/impl/file_win32.ipp
- include/boost/beast/http/impl/file_body_win32.ipp
- include/boost/beast/http/impl/read.ipp
- include/boost/beast/http/impl/write.ipp
- include/boost/beast/version.hpp
- include/boost/beast/websocket/detail/pausation.hpp
- include/boost/beast/websocket/impl/accept.ipp
- include/boost/beast/websocket/impl/close.ipp
- include/boost/beast/websocket/impl/handshake.ipp
- include/boost/beast/websocket/impl/ping.ipp
- include/boost/beast/websocket/impl/read.ipp
- include/boost/beast/websocket/impl/teardown.ipp
- include/boost/beast/websocket/impl/write.ipp
- include/boost/beast/websocket/stream.hpp
- subtree/unit_test/include/boost/beast/unit_test/dstream.hpp
- test/bench/wsload/wsload.cpp
- test/doc/http_snippets.cpp
* Add CppCon2017 presentation link
* Update README.md
* Update stream write documentation for end of stream changes
* Tidy up unused variable warnings
* Don't return end_of_stream on win32 file body writes
* Fix doc typo
* Fix shadowing in session_alloc
* Fix executor type compilation
* Add Travis tests with the default compilers
* Update Boost.WinAPI usage to the new location and namespace.
* Fix buffered_read_stream async_read_some signature
> Version 126

- CHANGELOG.md
- CMakeLists.txt
- doc/qbk/07_concepts/BodyReader.qbk
- doc/qbk/07_concepts/BodyWriter.qbk
- doc/qbk/07_concepts/FieldsWriter.qbk
- include/boost/beast/http/detail/chunk_encode.hpp
- include/boost/beast/version.hpp
* ConstBufferSequence mandates pointer equivalence
* Add FieldsWriter constructor requirement
* Tidy up some documented constructor syntax
> Version 137

- CHANGELOG.md
- CMakeLists.txt
- doc/qbk/09_releases.qbk
- include/boost/beast/http/impl/fields.ipp
- include/boost/beast/version.hpp
* Fix typo in release notes
* Safe treatment of zero-length string arguments in basic_fields
* Some basic_fields operations now give the strong exception guarantee
> Version 159

- CHANGELOG.md
- CMakeLists.txt
- include/boost/beast/core/detail/type_traits.hpp
- include/boost/beast/core/impl/buffers_prefix.ipp
- include/boost/beast/core/impl/buffers_suffix.ipp
- include/boost/beast/version.hpp
This could fix a compile error on a particular configuration:
http://www.boost.org/development/tests/master/developer/output/teeks99-02-mc3-5-14-Docker-64on64-boost-bin-v2-libs-beast-test-beast-core-buffers_cat-test-clang-linux-3-5~c++14-debug-threadapi-pthread-threading-multi.html
> Version 166

- CHANGELOG.md
- CMakeLists.txt
- doc/qbk/03_core/6_composed.qbk
- example/echo-op/echo_op.cpp
- example/websocket/server/chat-multi/http_session.cpp
- include/boost/beast/core/bind_continuation.hpp
- include/boost/beast/core/detail/bind_handler.hpp
- include/boost/beast/core/detail/remap_post_to_defer.hpp
- include/boost/beast/version.hpp
- test/beast/core/CMakeLists.txt
- test/beast/core/Jamfile
- test/beast/core/bind_continuation.cpp
- test/beast/core/test_executor.hpp
* Handler binders use the associated allocator
* Add detail::bind_continuation
* Rewrite the echo-op example
> Version 214

- CHANGELOG.md
- CMakeLists.txt
- example/advanced/server-flex/advanced_server_flex.cpp
- example/advanced/server/advanced_server.cpp
- example/http/server/async-ssl/http_server_async_ssl.cpp
- example/http/server/async/http_server_async.cpp
- example/http/server/coro-ssl/http_server_coro_ssl.cpp
- example/http/server/coro/http_server_coro.cpp
- example/http/server/flex/http_server_flex.cpp
- example/http/server/stackless-ssl/http_server_stackless_ssl.cpp
- example/http/server/stackless/http_server_stackless.cpp
- example/http/server/sync-ssl/http_server_sync_ssl.cpp
- example/http/server/sync/http_server_sync.cpp
- example/websocket/server/chat-multi/http_session.cpp
- include/boost/beast/_experimental/test/stream.hpp
- include/boost/beast/_experimental/unit_test/main.ipp
- include/boost/beast/core/impl/file_stdio.ipp
- include/boost/beast/http/message.hpp
- include/boost/beast/version.hpp
- test/doc/http_snippets.cpp
* test::stream has deprecated lowest_layer for ssl
* MSVC uses ::fopen_s
> Version 242

- CHANGELOG.md
- CMakeLists.txt
- azure-pipelines.yml
- example/advanced/server/advanced_server.cpp
- example/http/server/fast/http_server_fast.cpp
- example/http/server/small/http_server_small.cpp
- example/websocket/server/chat-multi/chat_client.html
- include/boost/beast/core/basic_stream.hpp
- include/boost/beast/core/buffers_cat.hpp
- include/boost/beast/core/detail/service_base.hpp
- include/boost/beast/core/impl/async_base.hpp
- include/boost/beast/core/impl/basic_stream.hpp
- include/boost/beast/core/impl/buffers_cat.hpp
- include/boost/beast/http/impl/read.hpp
- include/boost/beast/http/impl/write.hpp
- include/boost/beast/version.hpp
- include/boost/beast/websocket/impl/accept.hpp
- test/beast/core/buffers_cat.cpp
- test/beast/ssl/Jamfile
- test/beast/websocket/Jamfile
- test/beast/websocket/_detail_prng.cpp
- test/beast/websocket/accept.cpp
- test/beast/websocket/handshake.cpp
- test/doc/http_snippets.cpp
- tools/blacklist.supp
- tools/coverage.sh
- tools/get-boost.sh
- tools/valgrind.supp
* Remove uses of the deprecated `buffers` function
* Remove uses of deprecated methods in websocket tests
* Remove redundant use of `static_string`
* Remove redundant template in service_base
* Expand CI matrix using Azure Pipelines
* Make chat websocket javascript client more user friendly
* `allocator_traits::construct` is used for user-defined types
* Add 1-element specialization for `buffers_cat`
* Fix `buffers_cat` iterator tests
* Don't pessimize-move
* Use steady_timer type
* Preserve operation_aborted on partial message
> Version 256

- CHANGELOG.md
- CMakeLists.txt
- Jamfile
- azure-pipelines.yml
- example/websocket/server/chat-multi/chat_client.html
- include/boost/beast/version.hpp
- include/boost/beast/websocket/detail/frame.hpp
- test/beast/http/message_fuzz.hpp
- test/beast/http/parser.cpp
* Fix separate compilation in CI
* Fix clang inititalization warning in websocket
* Remove redundant use of `yield_to` in parser tests
* Add VS 2019 AzP CI matrix item
* Clean up typo in chat websocket javascript client
> Version 258

- CHANGELOG.md
- CMakeLists.txt
- azure-pipelines.yml
- include/boost/beast/core/detail/buffers_range_adaptor.hpp
- include/boost/beast/core/detail/remap_post_to_defer.hpp
- include/boost/beast/core/impl/multi_buffer.hpp
- include/boost/beast/core/multi_buffer.hpp
- include/boost/beast/http/fields.hpp
- include/boost/beast/http/impl/fields.hpp
- include/boost/beast/version.hpp
- include/boost/beast/websocket/detail/prng.hpp
- include/boost/beast/websocket/detail/prng.ipp
- include/boost/beast/websocket/impl/stream.hpp
- include/boost/beast/websocket/impl/stream_impl.hpp
- test/beast/websocket/_detail_prng.cpp
- test/beast/websocket/read2.cpp
- test/beast/websocket/test.hpp
* Deduplicate `websocket::read_size_hint` definition
* Fix UB in websocket read tests
* Remove redundant includes in websocket
* Use `std::shared_ptr` in `test::stream`
* Simplify websocket::detail::prng
* Don't over-allocate in http::basic_fields
* Fix multi_buffer allocation alignment
* Tidy up buffers_range
> Version 261

- CHANGELOG.md
- CMakeLists.txt
- include/boost/beast/core/detail/sha1.ipp
- include/boost/beast/core/impl/multi_buffer.hpp
- include/boost/beast/core/impl/static_string.hpp
- include/boost/beast/http/basic_dynamic_body.hpp
- include/boost/beast/http/impl/fields.hpp
- include/boost/beast/http/impl/fields.ipp
- include/boost/beast/version.hpp
- test/beast/core/basic_stream.cpp
- test/beast/core/file_test.hpp
- test/beast/core/flat_stream.cpp
- test/beast/core/static_string.cpp
- test/beast/http/dynamic_body.cpp
* Handle overflow in max size calculation in `basic_dynamic_body`
* Fix unused variable warnings in tests
* Fix missing initializer warning in `basic_fields`
* Remove unused functions in `impl/static_string.hpp`
* Fix unused variable warning in `multi_buffer`
* Fix header-only compilation errors in some configurations
* Workaround for miscompilation in MSVC 14.2
> Version 264

- CHANGELOG.md
- CMakeLists.txt
- doc/qbk/release_notes.qbk
- doc/xsl/custom-overrides.xsl
- example/http/server/async-ssl/http_server_async_ssl.cpp
- example/http/server/async/http_server_async.cpp
- example/websocket/client/async-ssl/websocket_client_async_ssl.cpp
- include/boost/beast/_experimental/test/stream.hpp
- include/boost/beast/_experimental/unit_test/suite_list.hpp
- include/boost/beast/version.hpp
- include/boost/beast/websocket/detail/impl_base.hpp
- include/boost/beast/zlib/detail/inflate_stream.ipp
* Remove test framework's dependency on RTTI.
* Fix CVE-2016-9840 in zlib implementation.
* Fix TLS SNI handling in websocket_client_async_ssl example.
* Fix reuse of sliding window in WebSocket permessage_deflate.
* Fix accept error handling in http_server_async example.
* Move library-specific docca configuration to Beast.
* Remove dependency on RTTI in `test::stream`.
> Version 321

- CHANGELOG.md
- doc/qbk/release_notes.qbk
- include/boost/beast/core/string_type.hpp
This improves inter-conversion between string_view implementations. Some observable differences for users:
- core::string_view no longer supports the .to_string() or .clear() extensions from Utility
- code that relied on .max_size() returning .size(), needs to be fixed to .size() instead
- remove_suffix() and remove_prefix() were more lenient than the standard specs; be sure you don't rely on it clamping the argument to valid range
- BOOST_NO_CXX11_EXPLICIT_CONVERSION_OPERATORS no longer suppresses conversions to std::string
- core::string_view adds .contains() and various bugs fixed
This also revealed several bugs against Boost Utility, and two feature requests for Boost Core
> Issue #2417 use boost::core::string_view

- doc/qbk/04_http/09_custom_body.qbk
Actually, one mention still remains, which I cannot remove [unless
DigiCert changes their G4 Trusted Root CA certificate](https://github.com/boostorg/beast/blob/develop/example/common/root_certificates.hpp#L1134:~:text=pTREE)...
> Fix #2445 Remove mention of ptree

- include/boost/beast/http/impl/file_body_win32.hpp
The maximum number of bytes to write using TransmitFile cannot be
greater than INT_MAX - 1, otherwise the function fails with WSAEINVAL.
https://docs.microsoft.com/en-us/windows/win32/api/mswsock/nf-mswsock-transmitfile
The issue can be reproduced using the http-server-sync example, by
sending a GET request for a file larger than INTMAX.
e.g:
$ curl -v http://127.0.0.1:8080/ubuntu.iso -o ubuntu.iso
*   Trying 127.0.0.1:8080...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /ubuntu.iso HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.83.0
> Accept: */*
>
* Mark bundle as not …
> Fix large files transfer on Windows

- include/boost/beast/core/impl/multi_buffer.hpp
- include/boost/beast/core/multi_buffer.hpp
- include/boost/beast/http/fields.hpp
http::basic_fields::set_t::size() is unused
core::multi_buffer::list_type::size() is only compared to 1 (in shrink_to_fit()); compare iterators instead.
> Remove unnecessary constant_time_size

- include/boost/beast/core/detail/base64.ipp
> base64::decode initializes local variables.

- doc/qbk/release_notes.qbk
Should I add another api version bump commit so it's on top of the commit history?
> boost 1.81 release notes.

- include/boost/beast/websocket/detail/impl_base.hpp
A fix for #2574.
```
C:\PathTo\boost\libs\beast\include\boost/beast/websocket/detail/impl_base.hpp(455,38): error C2220: the following warning is treated as an error
C:\PathTo\boost\libs\beast\include\boost/beast/websocket/detail/impl_base.hpp(455,38): warning C4100: 'n_bytes': unreferenced formal parameter
```
> Avoid warnings about unused variable

- example/http/client/body/json_client.cpp
Tiny typo in example comments but confused a search I was doing. Enjoying learning beast, thanks.
> typo in the json client comment

- include/boost/beast/core/async_base.hpp
- include/boost/beast/http/impl/read.hpp
- include/boost/beast/websocket/impl/close.hpp
- include/boost/beast/websocket/impl/ping.hpp
- include/boost/beast/websocket/impl/read.hpp
- include/boost/beast/websocket/impl/teardown.hpp
- include/boost/beast/websocket/impl/write.hpp
- test/beast/core/async_base.cpp
- test/beast/http/CMakeLists.txt
- test/beast/http/Jamfile
- test/beast/http/any_completion_handler.cpp
- test/beast/websocket/CMakeLists.txt
- test/beast/websocket/Jamfile
- test/beast/websocket/any_completion_handler.cpp
This is a conceptual change in the recent asio version that is reflected in any_completion_handler.
1.82 change, as it's behaviour changing.
> Switched self-posting to the io-object's executor.

- include/boost/beast/core/detail/config.hpp
`.assign(error)` is not defined.
> operator= is used to assign ecs without loc.

- include/boost/beast/ssl/ssl_stream.hpp
This fixes a build error when using the async_handshake overload that accepts a buffer.
> Fix compile error due to incorrect ssl_stream async_handshake concept

- include/boost/beast/core/detail/bind_handler.hpp
- test/beast/core/bind_handler.cpp
Previously, the implementation of `bind_handler` made the assumption that the trait `boost::is_placeholder` would be false for types corresponding to values in the `std::placeholders` namespace.
However, boost/bind commit `c85b31e3d200dda2a73cf0027a82c6d8e29066f8`, `Support use of standard placeholders with boost::bind`, added a new header, `boost/bind/std_placeholders.hpp`, which adds specializations to
`boost::is_placeholder` for `std::placeholders` types.
When this header is included before a use of `boost::bind_handler`, it results in compiler errors like the following, due to an internal helper function having overloads for
`enable_if<boost::is_placeholder...>` and
`enable_if<std::is_placeholder...>`, which were previously assumed to be mutually exclusive, but for which both …
> Address bind_handler ambiguous overload error when boost/bind/std_placeholders.hpp is included

- example/websocket/client/awaitable/websocket_client_awaitable.cpp
The `fail` function is used in the other websocket examples, and presumably was included here for that reason.  However, it is not actually used in this example.
This PR removes the unused function.
> Remove unused failure reporting code

- include/boost/beast/websocket/impl/accept.hpp
- include/boost/beast/websocket/impl/stream_impl.hpp
Boost beast uses "upgrade" as the token for the "Connection" header, however rfc6455 defines otherwise.
https://www.rfc-editor.org/rfc/rfc6455#page-18
```
6.   The request MUST contain a |Connection| header field whose value MUST include the "Upgrade" token.
```
Confusingly other rfc's are not consistent in using it like this.
The server side should accept the value as case-insensitive but not all implementations honor this.
I've had issues with this in the field (Samsung TV's for example)
The other implementations I investigated all use "Upgrade".
C (libwebsockets)
https://github.com/warmcat/libwebsockets/blob/e8eb7d6bd66dde2156dbcd37b0e9048ed4006320/lib/roles/ws/client-ws.c#L168
Python (websockets)
https://github.com/aaugustin/websockets/blob/6dcac04c10c61dde9aa5be0374965c31f16e77f4/src/ …
> change upgrade to Upgrade as connection header value

- include/boost/beast/core/file_base.hpp
- include/boost/beast/http/basic_parser.hpp
- include/boost/beast/http/buffer_body.hpp
- include/boost/beast/http/detail/rfc7230.hpp
- include/boost/beast/http/empty_body.hpp
- include/boost/beast/http/impl/field.ipp
- include/boost/beast/http/parser.hpp
- include/boost/beast/http/type_traits.hpp
Implements #2676 .
@ednolan can you confirm this does it?
> headers using std::int8_t et al. include <csdint>.

- include/boost/beast/core/detail/type_traits.hpp
- include/boost/beast/websocket/detail/decorator.hpp
cf. https://github.com/boostorg/beast/issues/2535
> Reimplement (C++23) deprecated std::aligned_storage

- include/boost/beast/ssl/ssl_stream.hpp
> ssl_stream doesn't use BOOST_BEAST_ASYNC_TPARAM1 due to clang errors.

- .drone.star
- .github/workflows/ci.yml
- doc/qbk/01_intro/_intro.qbk
- include/boost/beast/core/detail/config.hpp
This is due to C++98 support being dropped, so 4.8 fails other libraries C++11 detection.
> set minimum gcc version to 5.0.

- .github/workflows/ci.yml
At the moment 3.1.1 can only be installed on x64.
> openssl is set to 1.1.1.2100 for x86

- doc/Jamfile
- include/boost/beast/_experimental/test/impl/stream.hpp
- include/boost/beast/_experimental/test/stream.hpp
- include/boost/beast/core/basic_stream.hpp
- include/boost/beast/core/detect_ssl.hpp
- include/boost/beast/core/impl/basic_stream.hpp
- include/boost/beast/ssl/ssl_stream.hpp
- test/beast/core/basic_stream.cpp
- test/beast/http/CMakeLists.txt
- test/beast/http/Jamfile
- test/beast/http/deferred.cpp
- test/beast/websocket/CMakeLists.txt
- test/beast/websocket/Jamfile
- test/beast/websocket/deferred.cpp
> Replace BOOST_ASIO_INITFN_RESULT_TYPE with BOOST_ASIO_INITFN_AUTO_RESULT_TYPE

- include/boost/beast/http/error.hpp
Fixes #2693 
I assume "operaetion" meant to be "operation".
> Fix typo in documentation

- include/boost/beast/core/impl/basic_stream.hpp
> Use the explicit type std::size_t when completing the transfer_op

- include/boost/beast/_experimental/test/impl/stream.hpp
- include/boost/beast/core/async_base.hpp
- include/boost/beast/core/detail/bind_handler.hpp
- test/beast/websocket/close.cpp
The existing code attempts to customize `asio::associated_executor` and other associators for `bind_wrapper` and `bind_front_wrapper`, leading to a situation where Asio consistently assumes the presence of an associated executor with the bound handlers. This results in [asio::detail::is_work_dispatcher_required](https://github.com/boostorg/asio/blob/2e49b21732e5d1bb3bb98f209164c30816b0bc79/include/boost/asio/detail/work_dispatcher.hpp#L42) always being set to true. Consequently, Asio wraps the bound handlers in [asio::detail::work_dispatcher](https://github.com/boostorg/asio/blob/2e49b21732e5d1bb3bb98f209164c30816b0bc79/include/boost/asio/detail/initiate_post.hpp#L148) before execution.
Consequently, everything wrapped in a `bind_wrapper` or `bind_front_wrapper` is scheduled twice on the …
> Specialize asio::associator for bind_wrapper and bind_front_wrapper

- include/boost/beast/_experimental/test/impl/stream.hpp
- include/boost/beast/_experimental/test/impl/stream.ipp
- include/boost/beast/_experimental/test/stream.hpp
- include/boost/beast/core/async_base.hpp
- include/boost/beast/core/detail/impl/read.hpp
- include/boost/beast/core/impl/buffered_read_stream.hpp
- include/boost/beast/http/impl/file_body_win32.hpp
- include/boost/beast/http/impl/read.hpp
- include/boost/beast/http/impl/write.hpp
- include/boost/beast/websocket/impl/ping.hpp
- include/boost/beast/websocket/impl/read.hpp
- include/boost/beast/websocket/impl/teardown.hpp
- include/boost/beast/websocket/impl/write.hpp
- test/beast/core/basic_stream.cpp
We cannot deprecate `beast::bind_front_handler` in favor of `asio::prepend` or `asio::append` because it has a [special overload](https://github.com/boostorg/beast/blob/667e9ea251e862fa7b62a3ee94054faef201702e/include/boost/beast/core/detail/bind_handler.hpp#L240) for cases when the handler is a member function pointer which enables code like this to work:
```C++
ws_.async_accept(
req,
beast::bind_front_handler(
&websocket_session::on_accept,
shared_from_this()));
```
While this pattern is only employed in examples and tests, all instances within the library itself can be replaces with `asio::prepend`.
> Replace internal uses of beast::bind_front_handler with asio::prepend

- doc/xsl/custom-overrides.xsl
- include/boost/beast/http/read.hpp
- include/boost/beast/http/write.hpp
- include/boost/beast/websocket/stream.hpp
> Fix the issue of paragraph separation in the documentation

- include/boost/beast/core/basic_stream.hpp
> Fix documentation for `basic_stream::expires_after`

- include/boost/beast/core/impl/buffers_cat.hpp
It seems we can't simply assume that the code for `past_end::operator*()` will never compile, as the following code clearly needs to handle that case:
```C++
return mp11::mp_with_index<
sizeof...(Bn) + 2>(
it_.index(), // Considering the index is a runtime value, the compiler needs to generate code for when it points to `past_end`
dereference{*this});
```
Fixes #2678
> Fix unreachable code warning in `buffers_cat.hpp`

- example/websocket/client/async-ssl-system-executor/websocket_client_async_ssl_system_executor.cpp
`host_` string should be updated after its usage in SSL_set_tlsext_host_name, otherwise this would cause an SSL handshake error.
> Update host string after SSL_set_tlsext_host_name

- CMakeLists.txt
This is the variable most other boost libraries use for initial selection of whether to build their tests [or they default to OFF].
To me this makes usage as a third_party, where I don't necessarily want to run all tests with every build, more consistent.
> Use BUILD_TESTING as the default value for Beast_BUILD_TESTS.

- Jamfile
Declare our own b2 feature for valgrind and adding the BOOST_USE_VALGRIND predef. This avoids dependency ordering problems since Beast doesn't depend on Boost.Context. Which is the lib that defines the other valgrind feature.
This change is needed to avoid build errors for this PR https://github.com/boostorg/boost/pull/854
> Replace use of context valgrind feature.

- include/boost/beast/http/impl/basic_parser.ipp
- test/beast/http/parser.cpp
This happens when:
* chunked encoding
* body is empty
* chunk has no extensions
* and put calls are really weird
> fix asserts, it's possible that we reach code only with 3 symbols

- include/boost/beast/core/detail/stream_base.hpp
- include/boost/beast/core/impl/basic_stream.hpp
- test/beast/core/basic_stream.cpp
Previously, the code only handled expired timers when the buffer was empty.
> Handle expired timers in basic_stream transfer_op

- include/boost/beast/http/impl/status.ipp
- include/boost/beast/http/status.hpp
- test/beast/http/status.cpp
Though this HTTP status is just a joke, it is supported by numerous HTTP implementations, including (but not limited to):
* [Python](https://github.com/python/cpython/blob/f79ffc879b919604ed5de22ece83825006cf9a17/Lib/http/__init__.py#L130)
* [POCO](https://github.com/pocoproject/poco/blob/bc29f30e5cf035e860b3d2c1fc5df570f01513ea/Net/include/Poco/Net/HTTPResponse.h#L90)
* [Golang](https://pkg.go.dev/net/http#StatusTeapot)
* [Rust `actix-web` crate](https://docs.rs/actix-web/4.6.0/actix_web/http/struct.StatusCode.html#associatedconstant.IM_A_TEAPOT)
So, I think it's also a good idea to support this HTTP status code in Beast.
Also, C++ is occasionally used for embedded programming, such as smart teapots, and I think it also justifies adding this status code :) :)
> Add 418 "I'm a teapot" HTTP status

- include/boost/beast/websocket/impl/write.hpp
- test/beast/websocket/write.cpp
> Partial writes don't cause bytes_transferred underflow

- .github/workflows/build.yml
- include/boost/beast/_experimental/http/impl/icy_stream.hpp
- include/boost/beast/_experimental/test/impl/stream.hpp
- include/boost/beast/core/detail/impl/read.hpp
- include/boost/beast/core/detect_ssl.hpp
- include/boost/beast/core/impl/basic_stream.hpp
- include/boost/beast/core/impl/buffered_read_stream.hpp
- include/boost/beast/core/impl/flat_stream.hpp
- include/boost/beast/http/impl/file_body_win32.hpp
- include/boost/beast/http/impl/read.hpp
- include/boost/beast/http/impl/write.hpp
- include/boost/beast/websocket/impl/accept.hpp
- include/boost/beast/websocket/impl/close.hpp
- include/boost/beast/websocket/impl/handshake.hpp
- include/boost/beast/websocket/impl/ping.hpp
- include/boost/beast/websocket/impl/read.hpp
- include/boost/beast/websocket/impl/write.hpp
This is required for the new `asio::cancel_at` and `asio::cancel_after` completion token adapters to work.
> get_executor() works on initiation objects

- .github/workflows/build.yml
- .github/workflows/fuzz.yml
- example/advanced/server-flex-awaitable/advanced_server_flex_awaitable.cpp
- example/http/client/awaitable-ssl/http_client_awaitable_ssl.cpp
- example/http/client/awaitable/http_client_awaitable.cpp
- example/http/server/awaitable/http_server_awaitable.cpp
- example/websocket/client/awaitable/websocket_client_awaitable.cpp
- example/websocket/server/awaitable/websocket_server_awaitable.cpp
- include/boost/beast/_experimental/test/impl/stream.hpp
- include/boost/beast/core/async_base.hpp
- include/boost/beast/core/impl/basic_stream.hpp
- include/boost/beast/core/impl/buffered_read_stream.hpp
- include/boost/beast/http/impl/read.hpp
- include/boost/beast/http/impl/write.hpp
- include/boost/beast/websocket/detail/impl_base.hpp
- include/boost/beast/websocket/impl/teardown.hpp
No need for `rebind_executor` as `asio::deferred` is now the default completion token.
> awaitable examples are simplified

- include/boost/beast/core/detail/bind_handler.hpp
`asio::associator<>` has got an extra template parameter that enables SFINAE-based partial specialization:
https://github.com/chriskohlhoff/asio/commit/4928948a6e607664ee0ab5590544def762a118ad"
> Fix friend declarations of asio::associator<>

- include/boost/beast/http/impl/write.hpp
- include/boost/beast/websocket/impl/accept.hpp
- include/boost/beast/websocket/impl/handshake.hpp
- include/boost/beast/websocket/impl/teardown.hpp
Using `asio::deferred` as a completion token defers the initiation of operations and creates a lazy operation which might even be discarded. We need to move mutating operations to the initiator function objects or the constructor of operation objects, which are guaranteed to run when the deferred operation is launched.
> Initiating functions no longer perform mutating operations

- .github/workflows/build.yml
- .github/workflows/fuzz.yml
- CMakeLists.txt
- example/advanced/server-flex-awaitable/CMakeLists.txt
- example/advanced/server-flex-awaitable/Jamfile
- example/advanced/server-flex-awaitable/advanced_server_flex_awaitable.cpp
- test/CMakeLists.txt
Boost.Scope triggers a strange internal compiler error in GCC 14:
```
/workspace/boost/libs/asio/include/boost/asio/impl/co_spawn.hpp: In function ‘boost::asio::awaitable<boost::asio::detail::awaitable_thread_entry_point, Executor> boost::asio::detail::co_spawn_entry_point(boost::asio::awaitable<void, AwaitableExecutor>*, co_spawn_state<Handler, Executor, Function>) [with Handler = boost::asio::cancellation_slot_binder<consign_handler<listen(listen(task_group&, boost::asio::ssl::context&, boost::asio::ip::tcp::endpoint, boost::beast::string_view)::_Z6listenR10task_groupRN5boost4asio3ssl7contextENS2_2ip14basic_endpointINS6_3tcpEEENS1_4core17basic_string_viewIcEE.Frame*)::<lambda(std::__exception_ptr::exception_ptr)>, boost::scope::scope_exit<task_group::adapt<listen(listen(task_group&, …
```
> Remove Boost.Scope dependency from examples

- include/boost/beast/websocket/impl/close.hpp
- include/boost/beast/websocket/stream.hpp
- test/beast/websocket/ping.cpp
> Improve documentation of websocket::stream::async_close

- doc/qbk/06_websocket/07_teardown.qbk
Previously, this link incorrectly pointed to teardown instead of async_teardown.
> Fix link to async_teardown in teardown document

- .github/workflows/build.yml
- include/boost/beast/websocket/impl/read.hpp
- test/beast/websocket/read1.cpp
> Use `handshake_timeout` for closing handshake during read operations
