- CHANGELOG.md
- CMakeLists.txt
- Jamfile
- example/advanced/server-flex/CMakeLists.txt
- example/advanced/server-flex/advanced_server_flex.cpp
- example/advanced/server/CMakeLists.txt
- example/advanced/server/advanced_server.cpp
- example/http/server/async-ssl/http_server_async_ssl.cpp
- example/http/server/async/http_server_async.cpp
- example/http/server/coro-ssl/http_server_coro_ssl.cpp
- example/http/server/coro/http_server_coro.cpp
- example/http/server/flex/http_server_flex.cpp
- example/http/server/stackless-ssl/http_server_stackless_ssl.cpp
- example/http/server/stackless/http_server_stackless.cpp
- example/http/server/sync-ssl/http_server_sync_ssl.cpp
- example/http/server/sync/http_server_sync.cpp
- include/boost/beast/core/detail/allocator.hpp
- include/boost/beast/core/detail/type_traits.hpp
- include/boost/beast/core/flat_buffer.hpp
- include/boost/beast/core/impl/flat_buffer.ipp
- include/boost/beast/core/impl/multi_buffer.ipp
- include/boost/beast/core/impl/static_buffer.ipp
- include/boost/beast/core/multi_buffer.hpp
- include/boost/beast/http/fields.hpp
- include/boost/beast/http/impl/fields.ipp
- include/boost/beast/version.hpp
- test/beast/http/chunk_encode.cpp
- test/beast/http/message.cpp
* Boost test matrix fixes
* Tidy up allocator usage
* Example HTTP server fixes
> Version 103

- CHANGELOG.md
- CMakeLists.txt
- Jamfile
- include/boost/beast/version.hpp
- test/beast/http/chunk_encode.cpp
- test/doc/websocket_snippets.cpp
- test/example/common/root_certificates.cpp
- test/example/common/server_certificate.cpp
* Fix compile error in websocket snippet
* Tidy up Jamfile and tests
> Set version to 105

- CHANGELOG.md
- CMakeLists.txt
- doc/qbk/02_examples.qbk
- example/advanced/server-flex/advanced_server_flex.cpp
- example/advanced/server/advanced_server.cpp
- example/http/server/async-ssl/CMakeLists.txt
- example/http/server/async-ssl/http_server_async_ssl.cpp
- example/http/server/async/CMakeLists.txt
- example/http/server/async/http_server_async.cpp
- example/http/server/coro-ssl/http_server_coro_ssl.cpp
- example/http/server/coro/http_server_coro.cpp
- example/http/server/flex/CMakeLists.txt
- example/http/server/flex/http_server_flex.cpp
- example/http/server/stackless-ssl/CMakeLists.txt
- example/http/server/stackless-ssl/http_server_stackless_ssl.cpp
- example/http/server/stackless/CMakeLists.txt
- example/http/server/stackless/http_server_stackless.cpp
- include/boost/beast/version.hpp
* Fix argument parsing in HTTP examples
* Don't use async_write_msg in examples
> Version 108

- CHANGELOG.md
- CMakeLists.txt
- include/boost/beast/version.hpp
- include/boost/beast/websocket/detail/pausation.hpp
- include/boost/beast/websocket/detail/pmd_extension.hpp
- include/boost/beast/websocket/detail/utf8_checker.hpp
- include/boost/beast/websocket/impl/close.ipp
- include/boost/beast/websocket/impl/ping.ipp
- include/boost/beast/websocket/impl/read.ipp
- include/boost/beast/websocket/impl/rfc6455.ipp
- include/boost/beast/websocket/impl/stream.ipp
- include/boost/beast/websocket/impl/write.ipp
- include/boost/beast/websocket/stream.hpp
- test/beast/websocket/accept.cpp
- test/beast/websocket/close.cpp
- test/beast/websocket/frame.cpp
- test/beast/websocket/handshake.cpp
- test/beast/websocket/ping.cpp
- test/beast/websocket/read.cpp
- test/beast/websocket/rfc6455.cpp
- test/beast/websocket/stream.cpp
- test/beast/websocket/test.hpp
- test/beast/websocket/utf8_checker.cpp
- test/beast/websocket/write.cpp
- test/extras/include/boost/beast/test/fail_counter.hpp
- test/extras/include/boost/beast/test/stream.hpp
* Fix utf8 check split code point at buffer end
* Refactor stream operations and tests plus coverage
* Suspended ops special members
> Version 111

- CHANGELOG.md
- CMakeLists.txt
- include/boost/beast/version.hpp
- include/boost/beast/websocket/impl/read.ipp
- test/beast/websocket/read.cpp
* Add test for issue 802
* Fix enum and non-enum in conditional exp. warning
> Version 121

- CHANGELOG.md
- CMakeLists.txt
- example/http/server/async-ssl/http_server_async_ssl.cpp
- example/http/server/async/http_server_async.cpp
- example/http/server/coro-ssl/http_server_coro_ssl.cpp
- example/http/server/coro/http_server_coro.cpp
- example/http/server/fast/http_server_fast.cpp
- example/http/server/flex/http_server_flex.cpp
- example/http/server/small/http_server_small.cpp
- example/http/server/stackless-ssl/http_server_stackless_ssl.cpp
- example/http/server/stackless/http_server_stackless.cpp
- example/http/server/sync-ssl/http_server_sync_ssl.cpp
- example/http/server/sync/http_server_sync.cpp
- include/boost/beast/http/fields.hpp
- include/boost/beast/http/impl/write.ipp
- include/boost/beast/http/write.hpp
- include/boost/beast/version.hpp
- test/beast/http/write.cpp
- test/beast/websocket/accept.cpp
API Changes:
* http write returns success on connection close
* Fix for a test matrix compiler
* Use std::aligned_union
* Fix basic_fields javadoc
> Version 124

- CHANGELOG.md
- CMakeLists.txt
- doc/qbk/00_main.qbk
- doc/qbk/01_intro.qbk
- doc/qbk/02_examples.qbk
- doc/qbk/03_core/5_composed.qbk
- doc/qbk/04_http/02_message.qbk
- doc/qbk/04_http/04_serializer_streams.qbk
- doc/qbk/04_http/06_serializer_buffers.qbk
- doc/qbk/04_http/09_custom_body.qbk
- doc/qbk/04_http/10_custom_parsers.qbk
- doc/qbk/06_websocket/1_streams.qbk
- doc/qbk/06_websocket/2_connect.qbk
- doc/qbk/06_websocket/5_messages.qbk
- doc/qbk/06_websocket/8_notes.qbk
- doc/qbk/07_concepts/Body.qbk
- doc/qbk/07_concepts/BodyReader.qbk
- doc/qbk/08_design.qbk
- doc/qbk/08_design/1_http_message.qbk
- example/echo-op/echo_op.cpp
- include/boost/beast/http/impl/message.ipp
- include/boost/beast/version.hpp
* Add autobahn test report to doc
* Documentation tidying
* Fix prepare_payload: chunked is HTTP/1.1
> Version 129

- CHANGELOG.md
- CMakeLists.txt
- include/boost/beast/http/impl/serializer.ipp
- include/boost/beast/version.hpp
- include/boost/beast/websocket/detail/mask.hpp
- include/boost/beast/websocket/detail/utf8_checker.hpp
- include/boost/beast/zlib/detail/inflate_stream.hpp
- test/Jamfile
* Tidy up fallthrough warning
* Remove cxx11_sfinae_expr build requirement from tests
> Version 130

- CHANGELOG.md
- CMakeLists.txt
- example/http/client/async-ssl/http_client_async_ssl.cpp
- example/http/client/coro-ssl/http_client_coro_ssl.cpp
- example/http/client/sync-ssl/http_client_sync_ssl.cpp
- include/boost/beast/http/fields.hpp
- include/boost/beast/http/impl/fields.ipp
- include/boost/beast/version.hpp
* basic_fields returns const values
* Set SNI hostname in example SSL clients
> Version 131

- CHANGELOG.md
- CMakeLists.txt
- include/boost/beast/http/message.hpp
- include/boost/beast/version.hpp
- test/beast/http/message.cpp
* Remove const&& overload of message::body
> Version 133

- CHANGELOG.md
- CMakeLists.txt
- include/boost/beast/core/flat_static_buffer.hpp
- include/boost/beast/core/impl/flat_buffer.ipp
- include/boost/beast/core/impl/multi_buffer.ipp
- include/boost/beast/core/impl/read_size.ipp
- include/boost/beast/http/impl/basic_parser.ipp
- include/boost/beast/http/impl/file_body_win32.ipp
- include/boost/beast/version.hpp
- include/boost/beast/websocket/detail/pmd_extension.hpp
* Revisit boost library min/max guidance
> Version 139

- CHANGELOG.md
- CMakeLists.txt
- include/boost/beast/http/basic_parser.hpp
- include/boost/beast/http/impl/basic_parser.ipp
- include/boost/beast/http/impl/file_body_win32.ipp
- include/boost/beast/http/impl/read.ipp
- include/boost/beast/http/string_body.hpp
- include/boost/beast/http/vector_body.hpp
- include/boost/beast/version.hpp
- test/beast/http/read.cpp
- test/beast/websocket/utf8_checker.cpp
* Fix some integer warnings in 64-bit builds
* Fix utf8_checker test failures
* Fix signature for async_read_some, and tests
* Tidy up basic_parser
* Some basic_fields special members are protected
> Version 140

- CHANGELOG.md
- CMakeLists.txt
- include/boost/beast/http/message.hpp
- include/boost/beast/version.hpp
- test/doc/exemplars.cpp
> Version 141

- CHANGELOG.md
- CMakeLists.txt
- doc/qbk/07_concepts/BodyReader.qbk
- doc/qbk/07_concepts/BodyWriter.qbk
- doc/qbk/07_concepts/Fields.qbk
- doc/qbk/07_concepts/FieldsWriter.qbk
- include/boost/beast/version.hpp
- test/beast/http/write.cpp
* Warn about upcoming API changes to certain concepts
* Fix name typo in http write test
> Version 142

- CHANGELOG.md
- CMakeLists.txt
- README.md
- doc/qbk/01_intro.qbk
- include/boost/beast/version.hpp
> Version 143

- CHANGELOG.md
- CMakeLists.txt
- include/boost/beast/core/bind_handler.hpp
- include/boost/beast/core/detail/bind_handler.hpp
- include/boost/beast/core/detail/type_traits.hpp
- include/boost/beast/core/impl/buffered_read_stream.ipp
- include/boost/beast/http/impl/file_body_win32.ipp
- include/boost/beast/http/impl/read.ipp
- include/boost/beast/http/impl/write.ipp
- include/boost/beast/version.hpp
- include/boost/beast/websocket/impl/accept.ipp
- include/boost/beast/websocket/impl/close.ipp
- include/boost/beast/websocket/impl/handshake.ipp
- include/boost/beast/websocket/impl/ping.ipp
- include/boost/beast/websocket/impl/read.ipp
- include/boost/beast/websocket/impl/write.ipp
- test/extras/include/boost/beast/test/stream.hpp
* Type check completion handlers
* bind_handler doc update
* bind_handler works with boost placeholders
> Version 154

- CHANGELOG.md
- CMakeLists.txt
- example/advanced/server-flex/advanced_server_flex.cpp
- example/advanced/server/advanced_server.cpp
- include/boost/beast/core/bind_handler.hpp
- include/boost/beast/http/impl/serializer.ipp
- include/boost/beast/version.hpp
- include/boost/beast/websocket/detail/mask.hpp
- include/boost/beast/websocket/detail/stream_base.hpp
- include/boost/beast/websocket/impl/close.ipp
- include/boost/beast/websocket/impl/ping.ipp
- include/boost/beast/websocket/impl/read.ipp
- include/boost/beast/websocket/impl/stream.ipp
- include/boost/beast/websocket/impl/teardown.ipp
- include/boost/beast/websocket/impl/write.ipp
- include/boost/beast/websocket/stream.hpp
- test/beast/websocket/close.cpp
- test/beast/websocket/ping.cpp
- test/beast/websocket/read2.cpp
- test/beast/websocket/write.cpp
* Fix memory leak in advanced server examples
* Fix soft-mutex assert in websocket stream
* Fix fallthrough warnings
* Tidy up bind_handler doc
> Version 155

- CHANGELOG.md
- CMakeLists.txt
- doc/docca/include/docca/doxygen.xsl
- doc/qbk/00_main.qbk
- doc/qbk/09_releases.qbk
- include/boost/beast/version.hpp
- include/boost/beast/websocket/detail/stream_base.hpp
- include/boost/beast/websocket/impl/close.ipp
- include/boost/beast/websocket/impl/ping.ipp
- include/boost/beast/websocket/impl/read.ipp
- include/boost/beast/websocket/impl/write.ipp
- include/boost/beast/websocket/stream.hpp
- test/beast/websocket/ping.cpp
* Don't use typeid
* Add release notes to documentation
* Fix stale link for void-or-deduced
> Version 156

- CHANGELOG.md
- CMakeLists.txt
- doc/qbk/09_releases.qbk
- example/websocket/client/async-ssl/websocket_client_async_ssl.cpp
- example/websocket/client/async/websocket_client_async.cpp
- example/websocket/client/coro-ssl/websocket_client_coro_ssl.cpp
- example/websocket/client/coro/websocket_client_coro.cpp
- include/boost/beast/version.hpp
- include/boost/beast/websocket/detail/mask.hpp
- include/boost/beast/websocket/impl/teardown.ipp
- include/boost/beast/websocket/stream.hpp
* Fix teardown for TIME_WAIT
* Fix big-endian websocket masking
> Version 157

- CHANGELOG.md
- CMakeLists.txt
- doc/qbk/09_releases.qbk
- example/advanced/server-flex/advanced_server_flex.cpp
- example/advanced/server/advanced_server.cpp
- example/http/server/async-ssl/http_server_async_ssl.cpp
- example/http/server/async/http_server_async.cpp
- example/http/server/stackless-ssl/http_server_stackless_ssl.cpp
- example/http/server/stackless/http_server_stackless.cpp
- include/boost/beast/version.hpp
* Examples clear the HTTP message before reading
> Version 160

- CHANGELOG.md
- CMakeLists.txt
- example/common/detect_ssl.hpp
- include/boost/beast/core/buffered_read_stream.hpp
- include/boost/beast/http/read.hpp
- include/boost/beast/http/write.hpp
- include/boost/beast/version.hpp
- include/boost/beast/websocket/impl/write.ipp
- include/boost/beast/websocket/ssl.hpp
- include/boost/beast/websocket/stream.hpp
- include/boost/beast/websocket/teardown.hpp
- test/beast/websocket/accept.cpp
- test/beast/websocket/close.cpp
- test/beast/websocket/handshake.cpp
- test/beast/websocket/ping.cpp
- test/beast/websocket/read2.cpp
- test/beast/websocket/test.hpp
- test/beast/websocket/write.cpp
* Don't copy the handler in write_some_op
* Add move-only handler tests
* Fix handler parameter javadocs
> Version 161

- CHANGELOG.md
- CMakeLists.txt
- Jamfile
- doc/qbk/09_releases.qbk
- include/boost/beast/core/detail/bind_handler.hpp
- include/boost/beast/core/impl/buffered_read_stream.ipp
- include/boost/beast/http/impl/file_body_win32.ipp
- include/boost/beast/http/impl/read.ipp
- include/boost/beast/http/impl/write.ipp
- include/boost/beast/version.hpp
- include/boost/beast/websocket/impl/accept.ipp
- include/boost/beast/websocket/impl/close.ipp
- include/boost/beast/websocket/impl/handshake.ipp
- include/boost/beast/websocket/impl/ping.ipp
- include/boost/beast/websocket/impl/read.ipp
- include/boost/beast/websocket/impl/teardown.ipp
- include/boost/beast/websocket/impl/write.ipp
- include/boost/beast/websocket/stream.hpp
- test/beast/core/bind_handler.cpp
- test/beast/core/buffered_read_stream.cpp
- test/beast/http/read.cpp
- test/beast/http/write.cpp
- test/beast/websocket/accept.cpp
- test/beast/websocket/close.cpp
- test/beast/websocket/handshake.cpp
- test/beast/websocket/ping.cpp
- test/beast/websocket/read2.cpp
- test/beast/websocket/write.cpp
- test/extras/include/boost/beast/test/stream.hpp
* Add asio_handler_invoke overloads for stream algorithms
* Improve websocket::stream::control_callback javadoc
> Version 162

- CHANGELOG.md
- CMakeLists.txt
- example/common/detect_ssl.hpp
- include/boost/beast/core/impl/buffered_read_stream.ipp
- include/boost/beast/http/impl/read.ipp
- include/boost/beast/http/impl/write.ipp
- include/boost/beast/version.hpp
- include/boost/beast/websocket/detail/mask.hpp
- include/boost/beast/websocket/impl/accept.ipp
- include/boost/beast/websocket/impl/close.ipp
- include/boost/beast/websocket/impl/ping.ipp
- include/boost/beast/websocket/impl/read.ipp
- include/boost/beast/websocket/impl/teardown.ipp
- include/boost/beast/websocket/impl/write.ipp
* Tidy up calls to post()
* Fix narrowing warnings
> Version 163

- CHANGELOG.md
- CMakeLists.txt
- doc/qbk/09_releases.qbk
- include/boost/beast/http/field.hpp
- include/boost/beast/http/impl/field.ipp
- include/boost/beast/version.hpp
- include/boost/beast/websocket/detail/mask.hpp
- test/beast/http/field.cpp
- tools/field.txt
* Fix masking on continuation frames
* Add Access-Control-Expose-Headers field constant
> Version 164

- CHANGELOG.md
- CMakeLists.txt
- example/common/detect_ssl.hpp
- include/boost/beast/core/impl/buffered_read_stream.ipp
- include/boost/beast/http/impl/read.ipp
- include/boost/beast/http/impl/write.ipp
- include/boost/beast/version.hpp
- include/boost/beast/websocket/impl/accept.ipp
- include/boost/beast/websocket/impl/close.ipp
- include/boost/beast/websocket/impl/ping.ipp
- include/boost/beast/websocket/impl/read.ipp
- include/boost/beast/websocket/impl/teardown.ipp
- include/boost/beast/websocket/impl/write.ipp
* Revert: Tidy up calls to post()
> Version 167

- CHANGELOG.md
- CMakeLists.txt
- doc/qbk/03_core/5_composed.qbk
- doc/qbk/quickref.xml
- include/boost/beast/core/detail/bind_handler.hpp
- include/boost/beast/experimental/core/flat_stream.hpp
- include/boost/beast/experimental/test/stream.hpp
- include/boost/beast/http/fields.hpp
- include/boost/beast/http/parser.hpp
- include/boost/beast/version.hpp
- include/boost/beast/websocket/stream.hpp
- test/beast/core/bind_handler.cpp
* Tidy up websocket stream javadocs
* Fix move-only arguments in bind_handler
* Fix http::parser constructor javadoc
* Tidy up test::stream javadocs
* Tidy up composed operation doc
> Version 172

- CHANGELOG.md
- CMakeLists.txt
- include/boost/beast/version.hpp
- test/beast/experimental/icy_stream.cpp
> Set version to 175

- CHANGELOG.md
- doc/qbk/00_main.qbk
- example/cppcon2018/http_session.cpp
- example/cppcon2018/listener.cpp
- example/cppcon2018/websocket_session.cpp
* Fix broken doc link
* example/cppcon2018 only requires C++11
> Version 189-hf1

- CHANGELOG.md
- CMakeLists.txt
- include/boost/beast/_experimental/core/ssl_stream.hpp
- include/boost/beast/_experimental/http/impl/icy_stream.ipp
- include/boost/beast/_experimental/test/impl/stream.ipp
- include/boost/beast/_experimental/test/stream.hpp
- include/boost/beast/core/impl/buffered_read_stream.ipp
- include/boost/beast/http/impl/read.ipp
- include/boost/beast/http/impl/write.ipp
- include/boost/beast/version.hpp
- include/boost/beast/websocket/detail/stream_base.hpp
- include/boost/beast/websocket/impl/accept.ipp
- include/boost/beast/websocket/impl/close.ipp
- include/boost/beast/websocket/impl/handshake.ipp
- include/boost/beast/websocket/impl/ping.ipp
- include/boost/beast/websocket/impl/read.ipp
- include/boost/beast/websocket/impl/stream.ipp
- include/boost/beast/websocket/impl/teardown.ipp
- include/boost/beast/websocket/impl/write.ipp
- include/boost/beast/websocket/stream.hpp
- test/beast/websocket/CMakeLists.txt
- test/beast/websocket/Jamfile
- test/beast/websocket/stream_explicit.cpp
- tools/build-and-test.sh
* Update ssl_stream signatures for networking changes
* Fix test::stream async_result transformation
* Tidy up test::stream
* Enable explicit instantiation of websocket::stream
> Version 193

- CHANGELOG.md
- CMakeLists.txt
- include/boost/beast/_experimental/core/detail/saved_handler.hpp
- include/boost/beast/_experimental/core/ssl_stream.hpp
- include/boost/beast/core/detail/config.hpp
- include/boost/beast/core/flat_buffer.hpp
- include/boost/beast/core/flat_static_buffer.hpp
- include/boost/beast/core/impl/flat_buffer.ipp
- include/boost/beast/core/impl/flat_static_buffer.ipp
- include/boost/beast/core/impl/multi_buffer.ipp
- include/boost/beast/core/impl/static_buffer.ipp
- include/boost/beast/core/multi_buffer.hpp
- include/boost/beast/core/static_buffer.hpp
- include/boost/beast/http/impl/read.ipp
- include/boost/beast/version.hpp
- include/boost/beast/websocket/impl/close.ipp
- include/boost/beast/websocket/impl/read.ipp
- test/beast/core/flat_buffer.cpp
- test/beast/core/flat_static_buffer.cpp
- test/beast/core/multi_buffer.cpp
- test/beast/core/static_buffer.cpp
- test/beast/websocket/read2.cpp
* http::async_read returns the right byte count on error
* Add net namespace alias
* Don't use-after-free in test
* Tidy up ssl_stream (experimental)
* Dynamic buffer improvements
> Version 194

- CHANGELOG.md
- CMakeLists.txt
- Jamfile
- README.md
- example/advanced/server-flex/Jamfile
- example/http/client/async-ssl/Jamfile
- example/http/client/coro-ssl/Jamfile
- example/http/client/sync-ssl/Jamfile
- example/http/server/async-ssl/Jamfile
- example/http/server/coro-ssl/Jamfile
- example/http/server/flex/Jamfile
- example/http/server/stackless-ssl/Jamfile
- example/http/server/sync-ssl/Jamfile
- example/websocket/client/async-ssl/Jamfile
- example/websocket/client/coro-ssl/Jamfile
- example/websocket/client/sync-ssl/Jamfile
- example/websocket/server/async-ssl/Jamfile
- example/websocket/server/coro-ssl/Jamfile
- example/websocket/server/stackless-ssl/Jamfile
- example/websocket/server/sync-ssl/Jamfile
- include/boost/beast/version.hpp
- test/Jamfile
- test/lib_ssl.cpp
* Don't link to OpenSSL needlessly (bjam)
* HTTPS URLs in README.md
> Version 234

- CHANGELOG.md
- CMakeLists.txt
- Jamfile
- example/common/root_certificates.hpp
- include/boost/beast/version.hpp
* root_certificates.hpp: brought in the server certificate
> Version 236

- CHANGELOG.md
- CMakeLists.txt
- include/boost/beast/ssl/ssl_stream.hpp
- include/boost/beast/version.hpp
* Move friend function template definition
> Version 249

- CHANGELOG.md
- CMakeLists.txt
- include/boost/beast/version.hpp
- include/boost/beast/websocket/impl/ping.hpp
- test/beast/websocket/ping.cpp
* Add idle ping suspend test
* Fix moved-from executor in idle ping timeout
> Version 255

- CHANGELOG.md
- CMakeLists.txt
- include/boost/beast/core/impl/multi_buffer.hpp
- include/boost/beast/version.hpp
* Fix deallocate in multi_buffer
> Version 262

- .travis.yml
- CHANGELOG.md
- CMakeLists.txt
- include/boost/beast/_experimental/unit_test/suite.hpp
- include/boost/beast/core/async_base.hpp
- include/boost/beast/core/detail/stream_base.hpp
- include/boost/beast/core/impl/basic_stream.hpp
- include/boost/beast/core/impl/file_stdio.ipp
- include/boost/beast/version.hpp
- test/bench/parser/nodejs_parser.hpp
* Add package for Travis config
* Fix signed/unsigned mismatch in file_stdio::seek
* basic_stream dtor cannot throw
* cmake: check policy first
* Add default dtors to satisfy -Wnon-virtual-dtor
* Multiple I/O of the same type is not supported
> Version 267

- CHANGELOG.md
- CMakeLists.txt
- README.md
- include/boost/beast/core/buffers_adaptor.hpp
- include/boost/beast/core/detail/buffer.hpp
- include/boost/beast/core/detail/ostream.hpp
- include/boost/beast/core/detail/sha1.hpp
- include/boost/beast/core/flat_buffer.hpp
- include/boost/beast/core/flat_static_buffer.hpp
- include/boost/beast/core/impl/buffers_adaptor.hpp
- include/boost/beast/core/impl/multi_buffer.hpp
- include/boost/beast/core/impl/static_buffer.ipp
- include/boost/beast/core/multi_buffer.hpp
- include/boost/beast/core/static_buffer.hpp
- include/boost/beast/http/impl/field.ipp
- include/boost/beast/version.hpp
- test/beast/core/buffers_adaptor.cpp
- test/beast/core/buffers_to_string.cpp
- test/beast/core/multi_buffer.cpp
- test/beast/core/ostream.cpp
- test/beast/core/test_buffer.hpp
- test/beast/http/file_body.cpp
fix #1863
* Added some comments
* Add 64-bit specific calculation
* Fix endian-dependence in digest
> Field digest is endian-independent:

- doc/qbk/06_websocket/02_handshaking.qbk
- doc/qbk/release_notes.qbk
- test/doc/websocket_2_handshaking.cpp
> Update Release Notes

- CHANGELOG.md
- CMakeLists.txt
- doc/qbk/01_intro/_intro.qbk
- include/boost/beast/_experimental/http/impl/icy_stream.hpp
- include/boost/beast/_experimental/test/impl/stream.hpp
- include/boost/beast/core/detail/impl/read.hpp
- include/boost/beast/core/detail/read.hpp
- include/boost/beast/core/impl/basic_stream.hpp
- include/boost/beast/core/impl/buffered_read_stream.hpp
- include/boost/beast/core/impl/flat_stream.hpp
- include/boost/beast/http/field.hpp
- include/boost/beast/http/impl/field.ipp
- include/boost/beast/http/impl/file_body_win32.hpp
- include/boost/beast/http/impl/read.hpp
- include/boost/beast/http/impl/write.hpp
- include/boost/beast/http/span_body.hpp
- include/boost/beast/ssl/ssl_stream.hpp
- include/boost/beast/version.hpp
- include/boost/beast/websocket/impl/accept.hpp
- include/boost/beast/websocket/impl/close.hpp
- include/boost/beast/websocket/impl/handshake.hpp
- include/boost/beast/websocket/impl/ping.hpp
- include/boost/beast/websocket/impl/read.hpp
- include/boost/beast/websocket/impl/write.hpp
- include/boost/beast/websocket/stream.hpp
- test/beast/core/async_base.cpp
- test/beast/core/stream_traits.cpp
- test/beast/http/CMakeLists.txt
- test/beast/http/Jamfile
- test/beast/http/field_compiles.cpp
closes #1926 
closes #1927
closes #1928
closes #1929
> Version 292

- CHANGELOG.md
- CMakeLists.txt
- include/boost/beast/core/basic_stream.hpp
- include/boost/beast/core/buffers_prefix.hpp
- include/boost/beast/core/impl/basic_stream.hpp
- include/boost/beast/version.hpp
- include/boost/beast/websocket/impl/read.hpp
- include/boost/beast/websocket/impl/stream_impl.hpp
- test/beast/core/basic_stream.cpp
closes #1932
closes #1938
closes #1933
closes #1939
> Version 293

- CHANGELOG.md
- CMakeLists.txt
- include/boost/beast/core/file_stdio.hpp
- include/boost/beast/http/impl/read.hpp
- include/boost/beast/version.hpp
- test/beast/http/read.cpp
> Version 294

- .dockers/ubuntu-20/user-config.jam
- CHANGELOG.md
- CMakeLists.txt
- doc/qbk/01_intro/1a_bishop_fox.qbk
- include/boost/beast/core/detail/tuple.hpp
- include/boost/beast/version.hpp
- test/beast/core/_detail_tuple.cpp
Cumulated changes to version 303 candidate
> Version 303 Candidate

- CHANGELOG.md
- CMakeLists.txt
- include/boost/beast/_experimental/test/stream.hpp
- include/boost/beast/version.hpp
- test/beast/_experimental/stream.cpp
> Candidate for Version 306

- .drone.star
- .drone/README.md
- .drone/boost-script.sh
- .drone/docs-script.sh
- .drone/linux-cxx-install.sh
- CHANGELOG.md
- CMakeLists.txt
- include/boost/beast/_experimental/test/detail/stream_state.hpp
- include/boost/beast/_experimental/test/detail/stream_state.ipp
- include/boost/beast/_experimental/test/impl/stream.hpp
- include/boost/beast/_experimental/test/impl/stream.ipp
- include/boost/beast/_experimental/test/stream.hpp
- include/boost/beast/core/impl/multi_buffer.hpp
- include/boost/beast/src.hpp
- include/boost/beast/version.hpp
- meta/libraries.json
- test/beast/_experimental/stream.cpp
- test/beast/core/async_base.cpp
- test/beast/core/buffered_read_stream.cpp
- test/beast/websocket/accept.cpp
- test/extras/include/boost/beast/test/yield_to.hpp
- tools/build-and-test.sh
Changes going into version 307
> Version 307 Candidate (draft)

- CHANGELOG.md
- test/extras/include/boost/beast/test/yield_to.hpp
> Workaround TSAN CI bug

- CHANGELOG.md
- include/boost/beast/websocket/impl/read.hpp
> Remove incorrect ASSERT in websocket read

- include/boost/beast/http/error.hpp
- include/boost/beast/http/impl/basic_parser.ipp
- include/boost/beast/http/impl/error.ipp
- test/beast/http/basic_parser.cpp
- test/beast/http/error.cpp
- test/beast/http/parser.cpp
> Add multiple content length error

- include/boost/beast/websocket/stream.hpp
Websocket timeout option APIs
fix #2449
> Websocket timeout option APIs

- doc/Jamfile
- include/boost/beast/_experimental/test/stream.hpp
- include/boost/beast/core/async_base.hpp
- include/boost/beast/core/buffers_generator.hpp
- include/boost/beast/core/buffers_range.hpp
- include/boost/beast/core/span.hpp
- include/boost/beast/http/fields.hpp
- include/boost/beast/http/message_generator.hpp
- include/boost/beast/websocket/error.hpp
This PR fixes lots of Doxygen broken links and errors that have probably been accumulating over time.
> Fix API reference

- .drone.star
- .drone/drone.bat
- CHANGELOG.md
- appveyor.yml
- azure-pipelines.yml
- doc/qbk/03_core/8_conf_macros.qbk
- doc/qbk/release_notes.qbk
- include/boost/beast/core/string_type.hpp
> Remove BOOST_BEAST_USE_STD_STRING_VIEW

- include/boost/beast/core/bind_handler.hpp
> Fix typo in bind_handler.hpp

- .drone.star
- include/boost/beast/_experimental/test/handler.hpp
- test/beast/websocket/read1.cpp
- test/beast/websocket/timer.cpp
The freebsd tests are getting a couple of errors.
> FreeBSD drone tests

- include/boost/beast/websocket/impl/stream_impl.hpp
- test/beast/core/tcp_stream.cpp
> Fixed timer usage inside basic_stream.

- example/advanced/server-flex-awaitable/advanced_server_flex_awaitable.cpp
- test/beast/_experimental/stream.cpp
fixing two minor that came up when building on my older machine.
> Minor fixes

- include/boost/beast/core/impl/basic_stream.hpp
- include/boost/beast/core/impl/buffers_cat.hpp
> No exceptions

- doc/qbk/02_examples/_examples.qbk
- example/http/client/CMakeLists.txt
- example/http/client/Jamfile
- example/http/client/methods/CMakeLists.txt
- example/http/client/methods/Jamfile
- example/http/client/methods/http_client_methods.cpp
> Minimalistic method examples.

- doc/qbk/03_core/8_conf_macros.qbk
- include/boost/beast/core/detail/config.hpp
- include/boost/beast/http/basic_file_body.hpp
- include/boost/beast/http/impl/file_body_win32.hpp
- test/beast/http/file_body.cpp
- commit 1 is a config option, that's surely useful
- commit 2 bugfix
- commit 3 a very useful feature.
> File body improve

- example/advanced/server-flex-awaitable/advanced_server_flex_awaitable.cpp
> server-flex-awaitable example resets parser.

- .drone.star
- .drone/drone.sh
- tools/build-and-test.sh
@klemens-morgenstern you had asked about caching to speed up the CI process. We are working on that in boostorg/url and I have copied those scripts to beast.
Checking the main boostorg/beast CI results from the past few days, a few tests aren't passing. The situation is better in the master branch and a bit worse in the develop branch. Likewise, this pull request has a few failing tests but they mostly match up with what's already occurring in the develop branch.
> Drone caching

- include/boost/beast/websocket/impl/ping.hpp
- include/boost/beast/websocket/stream.hpp
> Handler requirements of ping/pong are correct.

- include/boost/beast/core/detail/work_guard.hpp
> work_guard has license info.

- include/boost/beast/websocket/stream.hpp
> Update documentation for websocket::stream::async_write_some

- example/websocket/server/awaitable/websocket_server_awaitable.cpp
> fix: Unhandled Connection Closing in websocker_server_awaitable.cpp

- example/advanced/server-flex-awaitable/advanced_server_flex_awaitable.cpp
- example/advanced/server-flex/advanced_server_flex.cpp
- example/advanced/server/advanced_server.cpp
> Fix write loop in advanced server examples

- include/boost/beast/_experimental/test/impl/error.ipp
- include/boost/beast/core/impl/error.ipp
- include/boost/beast/http/impl/error.ipp
- include/boost/beast/websocket/impl/error.ipp
- include/boost/beast/zlib/impl/error.ipp
- test/beast/core/error.cpp
- test/beast/http/error.cpp
- test/beast/websocket/error.cpp
- test/beast/zlib/error.cpp
> Add non-allocating overload for error category message function

- README.md
> Update Visual Studio instructions in README

- include/boost/beast/core/flat_buffer.hpp
- include/boost/beast/core/flat_static_buffer.hpp
> Stronger buffer contract on flat_buffer and flat_static_buffer

- include/boost/beast/http/message.hpp
> Improve documentation for `http::message::prepare_payload()`

- include/boost/beast/websocket/ssl.hpp
- include/boost/beast/websocket/teardown.hpp
> Clarify `teardown` and `async_teardown` are customization points

- include/boost/beast/zlib/deflate_stream.hpp
- include/boost/beast/zlib/detail/deflate_stream.hpp
- include/boost/beast/zlib/detail/deflate_stream.ipp
> Fix zlib name conflicts

- include/boost/beast/http/impl/status.ipp
- include/boost/beast/http/status.hpp
- test/beast/http/status.cpp
https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
Resolves #2729
> Update status code list to conform with IANA registry

- include/boost/beast/http/serializer.hpp
> Improve documentation of http::serializer

- include/boost/beast/websocket/option.hpp
- include/boost/beast/websocket/stream.hpp
> Update documentation for websocket::permessage_deflate

- include/boost/beast/core/string_type.hpp
> Remove BOOST_BEAST_USE_STD_STRING_VIEW deprecation warning

- include/boost/beast/http/fields.hpp
- include/boost/beast/http/impl/fields.hpp
- test/beast/core/buffers_generator.cpp
- test/beast/http/fields.cpp
- test/doc/websocket_2_handshaking.cpp
> Fix basic_fields move assignment

- include/boost/beast/websocket/detail/impl_base.hpp
- include/boost/beast/websocket/impl/stream.hpp
- include/boost/beast/websocket/stream.hpp
- test/beast/websocket/handshake.cpp
This commit addresses the requirements outlined in issue #228, enhancing the module's functionality and supporting better status tracking.
This is my first commit to this repository. So, I need help.
I didn't know where to put the structure.
@ashtum
> Add get_status to stream

- include/boost/beast/core/impl/basic_stream.hpp
> basic_stream: Fix call to net::dispatch

- doc/qbk/02_examples/_examples.qbk
- doc/qbk/03_core/1_refresher.qbk
> Fixed docs typos

- CHANGELOG.md
- CMakeLists.txt
- doc/qbk/02_examples/_examples.qbk
- doc/qbk/release_notes.qbk
- example/http/client/CMakeLists.txt
- example/http/client/Jamfile
- example/http/client/async-local/CMakeLists.txt
- example/http/client/async-local/Jamfile
- example/http/client/async-local/http_client_async_local.cpp
- example/http/server/CMakeLists.txt
- example/http/server/Jamfile
- example/http/server/async-local/CMakeLists.txt
- example/http/server/async-local/Jamfile
- example/http/server/async-local/http_server_async_local.cpp
- example/websocket/client/CMakeLists.txt
- example/websocket/client/Jamfile
- example/websocket/client/async-local/CMakeLists.txt
- example/websocket/client/async-local/Jamfile
- example/websocket/client/async-local/websocket_client_async_local.cpp
- example/websocket/server/CMakeLists.txt
- example/websocket/server/Jamfile
- example/websocket/server/async-local/CMakeLists.txt
- example/websocket/server/async-local/Jamfile
- example/websocket/server/async-local/websocket_server_async_local.cpp
- include/boost/beast/version.hpp
> Add examples of Unix domain sockets

- include/boost/beast/core/detail/cpu_info.hpp
Proposed fix for https://github.com/boostorg/beast/issues/3003
> added cstdint include

- example/advanced/server/advanced_server.cpp
- example/websocket/server/async-ssl/websocket_server_async_ssl.cpp
- example/websocket/server/fast/websocket_server_fast.cpp
- example/websocket/server/stackless-ssl/websocket_server_stackless_ssl.cpp
- example/websocket/server/stackless/websocket_server_stackless.cpp
Recreation of original (#3020) pull requests to add return statements to examples.
> Add missing return statements to examples
